name: flutter_page_template
description: A template for create pages in your flutter app.
version: 0.0.6
homepage: https://github.com/Jamerson1000/flutter_page_template

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3

flutter: null
